### ISSUE TITLE
Submit this to maven

### ISSUE THREAD

**Issue by parkan** [multiformats/scala-multihash#1]
Dealing with the submission process makes me feel like

![giphy](https://cloud.githubusercontent.com/assets/204986/14969798/4be21be0-1092-11e6-8fe8-c4dc57eece13.gif)

Can someone help?

**Comment by yusefnapora** [comment]
done

**Comment by parkan** [comment]
Now more like 

![giphy](https://cloud.githubusercontent.com/assets/204986/16808871/440df60e-48ec-11e6-9261-a74837bc3c78.gif)
