### ISSUE TITLE
Move to Multiformats?

### ISSUE THREAD

**Issue by RichardLitt** [multiformats/scala-multihash#5]
Hey @yusefnapora!

Thanks so much for this. As you may know, we recently created the [Multiformats](//github.com/multiformats) organization to be a home for all of the multiformats - multiaddr, multihash, etc. Would you be interested in moving this repository to that organization? You would still have admin rights on the repository, but it would be a part of a wider organization. This would mean more relevant eyes on it (most likely) and better cross-repository issue tracking. We'd also add a line mentioning you as the original author, and of course your commits would stay the same. 

Of course, keeping it on your profile is also cool; we'll still link to this from the main multihash repository at github.com/multiformats/multihash.

Thanks for taking the time to read this. 👍 

Tracking issue, here: https://github.com/multiformats/multiformats/issues/4.

**Comment by parkan** [comment]
Sounds good to me. @yusefnapora if you're down I can transfer?

**Comment by yusefnapora** [comment]
@parkan @RichardLitt, sure, let's do it 👍

**Comment by parkan** [comment]
@RichardLitt let me know who I should transfer to

**Comment by RichardLitt** [comment]
@parkan I added you to the multiformats group. Could you transfer it to multiformats? You should be able to now.

**Comment by parkan** [comment]
done

**Comment by RichardLitt** [comment]
Sweet! Will probably PR with a README update over the next couple of days. You're awesome, thanks Arkadiy.
